server_url: http://127.0.0.1:8080
listen_addr: 127.0.0.1:8080
private_key_path: /var/lib/headscale/private.key
derp:
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  paths:
    - /etc/headscale/derp-example.yaml
  auto_update_enabled: true
  update_frequency: 24h
disable_check_updates: false
ephemeral_node_inactivity_timeout: 30m
# Postgres config
db_type: postgres
db_host: localhost
db_port: 5432
db_name: headscale
db_user: foo
db_pass: bar
tls_letsencrypt_hostname: ""
acl_policy_path: "/etc/headscale/acl.hujson"
dns_config:
  nameservers:
    - 1.1.1.1
  magic_dns: false
  base_domain: example.com
unix_socket: /run/headscale.sock
# headscale supports experimental OpenID connect support,
# it is still being tested and might have some bugs, please
# help us test it.
# OpenID Connect
# oidc:
#   issuer: "https://your-oidc.issuer.com/path"
#   client_id: "your-oidc-client-id"
#   client_secret: "your-oidc-client-secret"
#
#   # Domain map is used to map incomming users (by their email) to
#   # a namespace. The key can be a string, or regex.
#   domain_map:
#     ".*": default-namespace
